## Numpy array and basics

In [7]:
import numpy as np

### create array from list

In [8]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:", arr_2d)

1D Array: [1 2 3 4 5]
2D Array: [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [9]:
py_list = [1, 2, 3,]
print("Python list multiplication:", py_list*2)

py_array = np.array([1, 2, 3])
print("Python array multiplication:", py_array*2)

import time
start= time.time()
py_list = [i*2 for i in range(1000000)]
print("Time taken by Python list:", time.time() - start)

start = time.time()
py_array = np.arange(1000000)*2
print("Time taken by NumPy array:", time.time() - start)

Python list multiplication: [1, 2, 3, 1, 2, 3]
Python array multiplication: [2 4 6]
Time taken by Python list: 0.17150545120239258
Time taken by NumPy array: 0.11463451385498047


### creating array from scratch

In [10]:
zeros=np.zeros((3,4))
print ("zeros array :\n", zeros)

ones=np.ones((2,3))
print ("ones array :\n", ones)

full=np.full((2,2), 7)
print ("full array :\n", full)

random_array = np.random.rand(2,3)
print("Random array:\n", random_array)

sequence_array = np.arange(0, 11, 2)
print("Sequence array:\n", sequence_array)

zeros array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array :
 [[1. 1. 1.]
 [1. 1. 1.]]
full array :
 [[7 7]
 [7 7]]
Random array:
 [[0.1941068  0.33964103 0.81998363]
 [0.53416433 0.76839468 0.22742564]]
Sequence array:
 [ 0  2  4  6  8 10]


### Vector,Matrix and Tensor

In [11]:
vector = np.array([1, 2, 3])
print("Vector:", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)

Vector: [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64


### Array Reshaping

In [13]:
arr = np.arange(12)
print("Original array:", arr)

reshaped_arr = arr.reshape((3, 4))
print("Reshaped array:\n", reshaped_arr)

#flattened (returns a copy of the array collapsed into one dimension)
flattened_arr = reshaped_arr.flatten()
print("\n Flattened array:", flattened_arr)

#ravel (returns a flattened view of the array)
raveled_arr = reshaped_arr.ravel()
print("\n Raveled array:", raveled_arr)

transposed_arr = reshaped_arr.T
print("\n Transposed array:\n", transposed_arr)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
