In [1]:
import numpy as np

### Numpy array operations

In [2]:
arr = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
print("Basic Slicing:", arr[2:7]) 
print("Slicing with Step:", arr[1:8:2]) 
print("Negative Indexing:", arr[-3])

Basic Slicing: [3 4 5 6 7]
Slicing with Step: [2 4 6 8]
Negative Indexing: 8


In [4]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Specific element:", arr_2d[1, 2])
print("Entire row:", arr_2d[1])
print("Entire column:", arr_2d[:, 1])

Specific element: 6
Entire row: [4 5 6]
Entire column: [2 5 8]


In [7]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
print("Sorteed Array:", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
print("Sorted 2D Array along axis 0:\n", np.sort(arr_2d_unsorted, axis=0))

Sorteed Array: [1 1 2 3 4 5 5 6 9]
Sorted 2D Array along axis 0:
 [[1 1 4]
 [2 5 5]
 [3 6 9]]


### Filter

In [8]:
numbers = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers:", even_numbers)

Even Numbers: [ 2  4  6  8 10]


### Filter with mask

In [12]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [13]:
indices = [0, 2, 4]
print(numbers[indices])

where_indices = np.where(numbers > 5)
print("NP where:",numbers[where_indices])

[1 3 5]
NP where: [ 6  7  8  9 10]


In [14]:
condition_array = np.where(numbers > 5, 'true', 'false')
print(condition_array) 

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and removing data

In [16]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

combined = np.concatenate((arr1, arr2))
print( combined)

[ 1  2  3  4  5  6  7  8  9 10]


### Array compatability

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6 , 7])
c = np.array([7, 8, 9])

print("Compatability shapes",a.shape==c.shape)

Compatability shapes True


In [21]:
orignal =np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((orignal, new_row))
print(orignal)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((orignal, new_col))
print("With new column:\n",with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column:
 [[1 2 7]
 [3 4 8]]


In [22]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)  
print("Array after deletion:", deleted)

Array after deletion: [1 2 4 5]
